import React from 'react';
import ClientLayout from './layout'; // Import the client layout
import Navbar from '../components/helperComponents/Navbar';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          <Navbar />
          {children}
        </ClientLayout>
      </body>
    </html>
  );
} 